const videos=[
 {title:'भारत की बड़ी खबरें और आज का अपडेट',creator:'Hindustan Tube Pro',views:'1.2M',time:'3 hours ago',cat:'News',img:'https://storage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg',video:'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',dur:'8:32'},
 {title:'Kotlin for Android Development — 10 मिनट में सीखें',creator:'Android Dev',views:'100K',time:'1 day ago',cat:'Education',img:'https://storage.googleapis.com/gtv-videos-bucket/sample/images/ElephantsDream.jpg',video:'https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',dur:'10:04'},
 {title:'भारत दर्शन: काशी विश्वनाथ धाम का अद्भुत दृश्य',creator:'Bharat Darshan',views:'762K',time:'2 days ago',cat:'Devotion',img:'https://images.unsplash.com/photo-1561361058-c24cecae35ca?auto=format&fit=crop&w=900&q=80',video:'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',dur:'10:21'},
 {title:'भारतीय क्रिकेट की आज की सबसे बड़ी खबर',creator:'Sports India',views:'540K',time:'4 hours ago',cat:'Sports',img:'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=900&q=80',video:'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',dur:'6:12'},
 {title:'भारत की बेटी ने जीता सबका दिल',creator:'Bharat News',views:'524K',time:'5 hours ago',cat:'Entertainment',img:'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80',video:'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',dur:'8:45'},
 {title:'नई पीढ़ी के लिए भारत की नई तकनीक',creator:'Tech Bharat',views:'310K',time:'1 day ago',cat:'Education',img:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80',video:'https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',dur:'7:10'},
 {title:'आज का लाइव अपडेट — देश और दुनिया',creator:'HTP Live',views:'890K',time:'1 hour ago',cat:'Live',img:'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=900&q=80',video:'https://storage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',dur:'12:20'},
 {title:'मनोरंजन की दुनिया की ताजा खबरें',creator:'HTP Entertainment',views:'415K',time:'6 hours ago',cat:'Entertainment',img:'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=900&q=80',video:'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',dur:'5:44'}
];
const shorts=videos.slice(2,6);
function render(list=videos){document.getElementById('videoGrid').innerHTML=list.map((v,i)=>`<article class="card" onclick="openVideo(${videos.indexOf(v)})"><div class="thumb"><img src="${v.img}" loading="lazy"><span class="duration">${v.dur}</span></div><h3>${v.title}</h3><p>${v.creator} • ${v.views} views • ${v.time}</p></article>`).join('')}
function renderShorts(){document.getElementById('shortGrid').innerHTML=shorts.map((v,i)=>`<article class="short" onclick="openVideo(${videos.indexOf(v)})"><img src="${v.img}" loading="lazy"><div class="overlay"><b>${v.title}</b><div class="stats">♥ 12.5K &nbsp; 💬 3.2K &nbsp; ↗ Share</div></div></article>`).join('')}
function showView(id,btn){['homeView','shortsView','subscriptionsView','libraryView'].forEach(x=>document.getElementById(x).classList.toggle('hidden',x!==id));document.querySelectorAll('.bottom button').forEach(x=>x.classList.remove('navActive'));if(btn)btn.classList.add('navActive');window.scrollTo({top:0,behavior:'smooth'})}
function filterCat(cat,btn){document.querySelectorAll('.chips button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');render(cat==='All'?videos:videos.filter(v=>v.cat===cat));showView('homeView');}
function searchVideos(){const q=document.getElementById('searchInput').value.toLowerCase();render(videos.filter(v=>(v.title+v.creator+v.cat).toLowerCase().includes(q)));showView('homeView')}
function openVideo(i){const v=videos[i]||videos[0];document.getElementById('playerTitle').textContent=v.title;document.getElementById('playerMeta').textContent=`${v.creator} • ${v.views} views • ${v.time}`;const p=document.getElementById('player');p.src=v.video;document.getElementById('playerModal').classList.remove('hidden');p.play().catch(()=>{});}
function closeVideo(){const p=document.getElementById('player');p.pause();p.removeAttribute('src');p.load();document.getElementById('playerModal').classList.add('hidden')}
function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('htp-dark',document.body.classList.contains('dark'))}
function goHome(){showView('homeView');render()}
if(localStorage.getItem('htp-dark')==='true')document.body.classList.add('dark');render();renderShorts();
